module.exports = {

	//For migration in development
	development: {
		use_env_variable: 'postgres://nirjharlo:123456@localhost:5432/keywords_guru',
    dialect: 'postgres',
  	dialectOptions: {
			ssl: false,
    	native:true
		},
	},

	production: {
		use_env_variable: 'postgres://nirjharlo:123456@localhost:5432/keywords_guru',
		dialect: "pg",
		ssl: true,
		native: true,
		logging:null,
		pool: {
			maxConnections: 3
		}
	},

	Connections: {
		"development": {
			"use_env_variable": "DATABASE_URL",
			"dialect": "postgres",
			"protocol": "postgres",
			"port": 5432,
			"ssl": false,
			"native": true,
			"logging":null,
			"pool": {
				"maxConnections": 3
			}
		},
		"production": {
			"use_env_variable": "DATABASE_URL",
			"dialect": "pg",
			"ssl": true,
			"native": true,
			"logging":null,
			"pool": {
				"maxConnections": 3
			}
		}
	},
  mandrill_api_key: 'qSuyBBAtNCvaohnsBj34Jg',
  stripe: {
      TEST: {
          sk: 'sk_test_XQPdFja3dGkIKvfTc3gXMoiN',
          pk: 'pk_test_bhy535iEaGXv5Z9elBtJzoVq'
      },
      LIVE: {
          sk: 'sk_live_QVY6cnmMDE6DJK8kKHrQbwSd',
          pk: 'pk_live_UmyVyPA2dE41zDYAhhjdttYP'
      }
  },
  blacklist: [
		'rochellewhitepr',
		'fitmumformula',
		'aimeehannah',
		'rtr_blog',
		'quitegreat',
		'vervesearch',
		'elenavenndigi',
		'largerfamily',
		'rtsmediapr',
		'hannahkokoschka',
		'sellyourstory1',
		'socialcheshire',
		'fprovfoundation',
		'nadia_dailyself',
		'acemediaservice',
		'coffers83',
		'think_ts',
		'conistoncrafts',
		'rebeccacloggs',
		'brightandgood',
		'jellyrockpr',
		'tsncblog',
		'fashioninsight',
		'jessicasneddon',
		'interviewguests',
		'inspirationalma',
		'sarahtrademark',
		'efay_',
		'melandjake99',
		'sweetlikeali',
		'literallypr',
		'stressedmum01',
		'nikkipr',
		'diarydirectory',
		'allterrainkart',
		'rbrollson',
		'feniton2014',
		'christinapbooks',
		'a5967155',
		'gidalong',
		'jaime_rios75',
		'journorequests',
		'fpcomms',
		'food4_media',
		'prop4mediauk',
		'jonathanrober43',
		'weejendey',
		'whmeanor',
		'lilylolabeach',
		'_journorequest',
		'prjournorequest',
		'nqlondon',
		'amoreinvitation',
		'impresspr',
		'sophiaeattwood',
		'nick__howe',
		'lucysaunderspr',
		'theimaginaire',
		'printsquiffy',
		'saraheasycurry',
		'_journorequest',
		'jreqs',
		'afri_freelancer',
		'jendelelise4w',
		'thequeensintown',
		'inspiringv10',
		'jade_hadden',
		'bitcoinlovers2',
		'habitat_press',
		'clodagh_p',
		'homes4media',
		'pro_pr1',
		'agent_peebee',
		'journorequests',
		'thaar',
		'mayfairmusings',
		'design_orchard',
		'beckysbijoux',
		'butterflymum83',
		'afnan_fayez5',
		'clairew_uk',
		'wemammographers',
		'prjournorequest',
		'missohemgee',
		'daytrippermag1',
		'RochelleWhitePR',
		'FitMumFormula',
		'AimeeHannah',
		'RTR_Blog',
		'QuiteGreat',
		'VerveSearch',
		'ElenaVennDigi',
		'largerfamily',
		'RTSMediaPR',
		'hannahkokoschka',
		'SellYourStory1',
		'SocialCheshire',
		'FProvFoundation',
		'nadia_dailyself',
		'AceMediaService',
		'coffers83',
		'THINK_TS',
		'ConistonCrafts',
		'RebeccaCloggs',
		'brightandgood',
		'JellyRockPR',
		'tsncblog',
		'FashionInsight',
		'JessicaSneddon',
		'interviewguests',
		'InspirationalMa',
		'sarahTRADEMARK',
		'efay_',
		'melandjake99',
		'SweetLikeAli',
		'LiterallyPR',
		'stressedmum01',
		'NikkiPr',
		'DIARYdirectory',
		'AllTerrainKart',
		'RBrollson',
		'Feniton2014',
		'ChristinaPBooks',
		'a5967155',
		'gidalong',
		'jaime_rios75',
		'JournoRequests',
		'fpcomms',
		'Food4_Media',
		'Prop4MediaUK',
		'JonathanRober43',
		'weejendey',
		'whmeanor',
		'lilylolabeach',
		'_JournoRequest',
		'PRJournoRequest',
		'nqlondon',
		'AmoreInvitation',
		'impresspr',
		'SophiaEAttwood',
		'Nick__Howe',
		'lucysaunderspr',
		'theimaginaire',
		'PrintSquiffy',
		'saraheasycurry',
		'_JournoRequest',
		'jreqs',
		'Afri_Freelancer',
		'JenDelelisE4W',
		'TheQueensInTown',
		'inspiringv10',
		'Jade_Hadden',
		'bitcoinlovers2',
		'Habitat_Press',
		'clodagh_p',
		'homes4media',
		'PRO_PR1',
		'Agent_PeeBee',
		'JournoRequests',
		'thaar',
		'mayfairmusings',
		'Design_Orchard',
		'BeckysBijoux',
		'butterflymum83',
		'afnan_fayez5',
		'ClaireW_UK',
		'WeMammographers',
		'PRJournoRequest',
		'MissOhEmGee',
		'DayTripperMag1',
		'santinicolass1',
		'harris_group_uk',
		'carolinecarter4',
		'loualexa',
		'bakedtileco',
		'behindbras',
		'atidymind',
		'lilguys',
		'apdouk',
		'purelyamy_blog',
		'charlatanft',
		'clrsconchada',
		'jarntidowe',
		'sentibotr',
		'obeimar1011',
		'hellobravepr',
		'uptwnfm',
		'ms____official',
		'tagoe01',
		'veeno_uk',
		'dubeysarvesh552',
		'keithgrinsted',
		'vivekchouhan4'
  ]
};
